# Generated by Django 3.2.21 on 2023-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='account_active',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
