# Generated by Django 3.2.21 on 2023-10-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registry',
        ),
    ]
