# Generated by Django 4.2.9 on 2024-04-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
