# Generated by Django 3.2.21 on 2023-10-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20231006_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustomer',
        ),
    ]
