# Generated by Django 3.2.21 on 2023-10-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_usercustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.CharField(default='default_email', max_length=100, primary_key=True, serialize=False),
        ),
    ]
