# Generated by Django 4.2.9 on 2024-04-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='password',
        ),
    ]
