# Generated by Django 3.2.21 on 2024-01-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_calender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calender',
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='booking_length',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='reservations',
            name='date',
            field=models.DateField(default=19),
        ),
        migrations.AddField(
            model_name='reservations',
            name='end_time',
            field=models.TimeField(default=10),
        ),
        migrations.AddField(
            model_name='reservations',
            name='start_time',
            field=models.TimeField(default=10),
        ),
    ]
