# Generated by Django 4.2.9 on 2024-04-10 13:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_reservations_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name=users.models.Customers),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='end_time',
            field=models.TimeField(default=13),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='start_time',
            field=models.TimeField(default=13),
        ),
    ]
