# Generated by Django 4.2.9 on 2024-04-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_reservations_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='end_time',
            field=models.TimeField(default=9),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='start_time',
            field=models.TimeField(default=9),
        ),
    ]
