# Generated by Django 4.2.9 on 2024-04-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_reservations_active_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='end_time',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='start_time',
            field=models.TimeField(default=0),
        ),
    ]
