# Generated by Django 4.2.9 on 2024-04-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_reservations_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='email',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='end_time',
            field=models.TimeField(default=23),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='start_time',
            field=models.TimeField(default=23),
        ),
    ]
